name: My TestBuild

on:
  push:
    branches:
      - main
      - mubashir's-Branch
      - master
  
  pull_request:
    branches:
      - main
      - master
      - mubashir's-Branch

# on:
#   schedule:
#     - cron:  '*/15 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Make Migrations and Migrate Models
      run: |
        python manage.py makemigrations
        python manage.py migrate
    - name: Code Quality Check Using Flake8
      run: |
        flake8
    - name: Coverage report
      run: |
        pip install coverage
        coverage run manage.py test
        coverage report
    - name: Django Genaral Testing
      run: |
        python3 manage.py test
